Repository spbu-math-cs-mse/tunelint, pull requests merged in 2024-11, with the labels that each got.

#18 Fix architecture
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/App.kt
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/filesupport/XMLParser.kt
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/model/changerequest/ChangeRequest.kt
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/model/changerequest/MelodyChangeRequestFactory.kt
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/model/changerequest/impl/AddSymbolToMeasureRequest.kt
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/model/changerequest/impl/AddSymbolToMelodyRequest.kt
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/model/changerequest/impl/RemoveSymbolToMelodyRequest.kt
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/model/core/Commands.kt
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/model/core/Measure.kt
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/model/core/Melody.kt
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/model/core/MusicFactory.kt
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/model/core/MutableMeasure.kt
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/model/core/MutableMelody.kt
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/model/core/impl/MeasureImpl.kt
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/model/core/impl/MelodyImpl.kt
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/model/musicsheetchangerequest/AddSymbolRequest.kt
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/model/musicsheetchangerequest/MusicSheetChangeRequest.kt
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/model/musicsheetchangerequest/RemoveSymbolRequest.kt
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/musicsheet/MusicSheet.kt
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/viewmodel/RedactorScreenViewModel.kt
Labels: good first issue

#28 Refactor model
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/interaction/handlers/impl/ReceiverImpl.kt
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/model/changerequest/PersistentRequestFactory.kt
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/model/changerequest/impl/AddSymbolPersistentRequest.kt
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/model/changerequest/impl/AddSymbolRequest.kt
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/model/changerequest/impl/RemoveSymbolPersistentRequest.kt
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/model/changerequest/impl/RemoveSymbolRequest.kt
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/model/core/NotePointer.kt
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/model/core/PointerFactory.kt
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/model/core/impl/NotePointerLastMeasure.kt
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/model/core/impl/NotePointerLastMelody.kt
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/model/core/impl/NotePointerSimple.kt
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/view/MusicSheetView.kt
Labels: enhancement

#33 PersistenceManager now tracks if undo and redo options are available
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/model/changerequest/PersistenceManager.kt
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/model/changerequest/impl/PersistenceManagerImpl.kt
Labels: enhancement

#35 More NotePointers
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/model/core/PointerFactory.kt
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/model/core/impl/NotePointerMeasureEternalLast.kt
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/model/core/impl/NotePointerMeasureInstantLast.kt
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/model/core/impl/NotePointerMelodyEternalEnd.kt
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/model/core/impl/NotePointerMelodyEternalLast.kt
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/model/core/impl/NotePointerMelodyInstantEnd.kt
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/model/core/impl/NotePointerMelodyInstantLast.kt
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/view/MusicSheetView.kt
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/view/viewable/impl/NoteViewableImpl.kt
Labels: enhancement

#42 Change measure mutation logic
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/model/changerequest/impl/AddSymbolRequest.kt
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/model/changerequest/impl/PersistenceManagerImpl.kt
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/model/changerequest/impl/RemoveSymbolRequest.kt
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/model/core/MutableMelody.kt
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/model/core/impl/MelodyImpl.kt
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/view/viewable/impl/MelodyViewableImpl.kt
Labels: enhancement

#44 Undo only successful requests
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/model/changerequest/Notifiable.kt
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/model/changerequest/impl/PersistenceManagerImpl.kt
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/model/changerequest/impl/RequestableMelodyImpl.kt
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/view/toolbar/ToolbarView.kt
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/view/viewable/impl/NotifiableMelodyViewableImpl.kt
Labels: enhancement

#56 fix click near measure line
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/view/musicsheet/MusicSheetView.kt
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/view/musicsheet/composable/MeasureLine.kt
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/view/musicsheet/composable/MelodyView.kt
Labels: bug

#52 UI horizontal/vertical toolbar
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/App.kt
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/interaction/Interactor.kt
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/interaction/InteractorImpl.kt
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/model/changerequest/PersistenceManager.kt
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/model/changerequest/impl/PersistenceManagerImpl.kt
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/musicsheet/MusicSheet.kt
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/view/toolbar/HorizontalToolbarView.kt
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/view/toolbar/ToolbarView.kt
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/view/toolbar/VerticalToolbarView.kt
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/viewmodel/RedactorScreenViewModel.kt
Labels: invalid

#23 Support files for real
  composeApp/build.gradle.kts
  composeApp/music/parser_test_input_1.xml
  composeApp/music/parser_test_input_2.xml
  composeApp/music/test.xml
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/filesupport/XMLParser.kt
  composeApp/src/commonMain/test/filesupport/XMLParserTest.kt
  composeApp/src/commonTest/kotlin/org/goalteam/tunelint/filesupport/XMLParserTest.kt
Labels: enhancement, good first issue

#59 File-support quickfix
  composeApp/src/commonMain/kotlin/org/goalteam/tunelint/filesupport/XMLParser.kt
Labels: bug
